export const todoAction = {
  ADD_TODO: "ADD_TODO",
  EDITING_TODO: "EDITING_TODO",
  EDITED_TODO: "EDITED_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  MARK_COMPLETED: "MARK_COMPLETED",
  MARK_INCOMPLETED: "MARK_INCOMPLETED",
  FILTER_TODOS: "FILTER_TODOS",
  MARK_ALL_COMPLETED: "MARK_ALL_COMPLETED",
  UPDATE_SEARCH_TERM: "UPDATE_SEARCH_TERM",
};
